### ISSUE TITLE
Projectを抜いてFeedbackとして統一してよいと思います。42apiのフィードバックを使うときに区別すればいいです。このプルリクで修正するかはお任せします。

### ISSUE THREAD

**Issue by yshima42** [yshima42/42feedback#49]
Projectを抜いてFeedbackとして統一してよいと思います。42apiのフィードバックを使うときに区別すればいいです。このプルリクで修正するかはお任せします。

_Originally posted by @hyoshie in https://github.com/yshima42/42progress/issues/48#issuecomment-1420183073_

**Comment by hyoshie** [comment]
対応済み
